In [1]:
#import modules and set up environment 
import os
import sys
path = "../../src/"

sys.path.append(path)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import jax.numpy as jnp
from jax import jit, grad, vmap, hessian, scipy, random

In [34]:
#import sgmcmc code 
import models.logistic_regression.logistic_regression as lr
import samplers.sgld as sgld
import samplers.sgldps as sgldps
import samplers.sgldcv as sgldcv
import samplers.sgldcvps as sgldcvps
import samplers.sgd as sgd

key = random.PRNGKey(0)

### Set up model and data

In [3]:
#load in the data
file_path = "../../data/synthetic/toy_lr_balance_train_synth.csv"
data = pd.read_csv(file_path)
dat_array = data.values[:]
x = dat_array[:, 1:]
y = dat_array[:,0]

In [4]:
#set up model parameters
N = x.shape[0]
dim = x.shape[1] 

#priors
mu_0 = np.zeros(dim) #prior mean
lambda_0 = 10.0*np.eye(dim)  #prior covariance matrix

In [5]:
#set up model-specific gradient functions
gradf_0 = lr.gradf_0
gradf_i_batch = lr.gradf_i_batch
post_var = lr.post_var

### Find mode using SGD

In [6]:
#hyperparameters for SGD
n_sgd = int(0.01*N)
Niter_sgd = 10**4
step_sgd = 1e-3

In [7]:
#draw theta_0 from the prior
theta_start = jnp.zeros(dim) #random starting value
print("Initalising SGD to find mode at theta_0:\n", theta_start)

Initalising SGD to find mode at theta_0:
 [0. 0. 0. 0. 0.]


In [8]:
theta_hat, samples_sgd, run_time = sgd.adam(key, gradf_0, gradf_i_batch, Niter_sgd, theta_start, x, y, n_sgd, step_sgd, replacement=True)

In [9]:
theta_hat

array([-0.9348976 , -0.41609308, -1.22440743,  0.36571023, -0.8317759 ])

In [10]:
# draw candidate thetas
n_candidate = 10
sigma_hat = post_var(theta_hat, x,y)[0]
theta_candidates = random.multivariate_normal(key=key, mean = theta_hat, cov= sigma_hat, shape=(n_candidate,))
theta_candidates

DeviceArray([[-0.9683532 , -0.49170724, -1.3405797 ,  0.38402447,
              -0.9073683 ],
             [-1.0635264 , -0.4388886 , -1.2785772 ,  0.38747898,
              -0.8468758 ],
             [-0.9769268 , -0.45872605, -1.2457107 ,  0.39358127,
              -0.93533677],
             [-1.3089921 , -0.34126902, -1.2269322 ,  0.47543913,
              -0.89157206],
             [-0.9981764 , -0.38148248, -1.1538057 ,  0.35715896,
              -0.9293198 ],
             [-0.66766846, -0.51894903, -1.1942793 ,  0.21381217,
              -0.9099646 ],
             [-0.83467466, -0.40973818, -1.1823505 ,  0.3357298 ,
              -0.76768553],
             [-0.9066595 , -0.4267365 , -1.1557379 ,  0.4286306 ,
              -0.7331321 ],
             [-1.0963364 , -0.3834407 , -1.2176023 ,  0.45045567,
              -0.8945911 ],
             [-0.989809  , -0.49958813, -1.3074896 ,  0.32732075,
              -0.96823853]], dtype=float32)

### Set up experiment 

In [11]:
batch_sizes = jnp.int32(jnp.linspace(0.01, 0.99, num=50)*N)

In [12]:
pseudo_var = dict()
reps = 1000

### SGLD gradients (with replacement)

In [13]:
pseudo_var['sgld-wr'] = np.zeros((n_candidate, batch_sizes.shape[0])) 
#sgld (wr) gradients
for i in tqdm(range(n_candidate), desc = "Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgld_gradients1 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgld.sgld_grad(subkey, theta_candidate, gradf_0, gradf_i_batch, x, y, n, replacement=True)
            sgld_gradients1[k] = grad
        pseudo_var['sgld-wr'][i,j] = np.sum(np.var(sgld_gradients1, axis = 0))

Theta candidates tested: 100%|██████████| 10/10 [04:50<00:00, 29.07s/it]


### SGLD gradients (without replacement)

In [14]:
pseudo_var['sgld-wor'] = np.zeros((n_candidate, batch_sizes.shape[0])) 
#sgld (wor) gradients
for i in tqdm(range(n_candidate), desc = "Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgld_gradients2 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgld.sgld_grad(subkey, theta_candidate, gradf_0, gradf_i_batch, x, y, n, replacement=False)
            sgld_gradients2[k] = grad
        pseudo_var['sgld-wor'][i,j] = np.sum(np.var(sgld_gradients2, axis = 0))

Theta candidates tested: 100%|██████████| 10/10 [13:08<00:00, 78.89s/it]


### SGLD-PS (exact probabilities)

In [15]:
#sgld-ps (exact) gradients
pseudo_var['sgld-ps-exact'] = np.zeros((n_candidate, batch_sizes.shape[0])) 

In [16]:
for i in tqdm(range(n_candidate), desc = "Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    probs1 = sgldps.exact_probs(theta_candidate, gradf_i_batch, x, y)
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgldps_gradients1 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgldps.sgldps_grad(subkey, theta_candidate, gradf_0, gradf_i_batch, probs1, x, y, n)
            sgldps_gradients1[k] = grad
        pseudo_var['sgld-ps-exact'][i,j] = np.sum(np.var(sgldps_gradients1, axis = 0))

Theta candidates tested: 100%|██████████| 10/10 [13:43<00:00, 82.34s/it]


### SGLD-PS (approximate probabilities)

In [17]:
#sgld-ps (approx) gradients
f_i_grad_list = sgldps.ps_preliminaries(theta_hat, gradf_i_batch, x, y)
probs2 = sgldps.approx_probs(theta_hat, f_i_grad_list)
pseudo_var['sgld-ps-approx'] = np.zeros((n_candidate, batch_sizes.shape[0])) 

In [18]:
for i in tqdm(range(n_candidate), desc = " Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgldps_gradients2 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgldps.sgldps_grad(subkey, theta_candidate, gradf_0, gradf_i_batch, probs2, x, y, n)
            sgldps_gradients2[k] = grad
        pseudo_var['sgld-ps-approx'][i, j] = np.sum(np.var(sgldps_gradients2, axis = 0))

 Theta candidates tested: 100%|██████████| 10/10 [12:58<00:00, 77.88s/it]


### SGLD-CV gradients (with replacement)

In [19]:
gradf_0_hat, grad_full_hat, f_i_grad_list = sgldcv.cv_preliminaries(theta_hat, gradf_0, gradf_i_batch, x, y)

In [20]:
pseudo_var['sgld-cv-wr'] = np.zeros((n_candidate, batch_sizes.shape[0])) 

#sgldcv gradients
for i in tqdm(range(n_candidate), desc = "Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgldcv_gradients1 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgldcv.sgld_cv_grad(subkey, theta_candidate, theta_hat, gradf_0, gradf_i_batch, grad_full_hat, f_i_grad_list, x, y, n, replacement=True)
            sgldcv_gradients1[k] = grad
        pseudo_var['sgld-cv-wr'][i, j] = np.sum(np.var(sgldcv_gradients1, axis = 0))

Theta candidates tested: 100%|██████████| 10/10 [08:34<00:00, 51.40s/it]


### SGLD-CV gradients (without replacement)

In [21]:
pseudo_var['sgld-cv-wor'] = np.zeros((n_candidate, batch_sizes.shape[0])) 

#sgldcv gradients
for i in tqdm(range(n_candidate), desc = "Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgldcv_gradients2 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgldcv.sgld_cv_grad(subkey, theta_candidate, theta_hat, gradf_0, gradf_i_batch, grad_full_hat, f_i_grad_list, x, y, n, replacement=False)
            sgldcv_gradients2[k] = grad
        pseudo_var['sgld-cv-wor'][i, j] = np.sum(np.var(sgldcv_gradients2, axis = 0))

Theta candidates tested: 100%|██████████| 10/10 [17:23<00:00, 104.32s/it]


### SGLD-CV-PS (exact probabilities) gradients

In [22]:
cov_mat = sgldcvps.cvps_preliminaries(theta_hat, gradf_0, gradf_i_batch, post_var, x, y)[0]
f_i_hess_list = sgldcvps.cvps_preliminaries(theta_hat, gradf_0, gradf_i_batch, post_var, x, y)[4]

In [23]:
#sgld-cv-ps (exact) gradients
pseudo_var['sgld-cv-exact'] = np.zeros((n_candidate, batch_sizes.shape[0])) 

for i in tqdm(range(n_candidate), desc = " Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    probs3 = sgldcvps.exact_probs(theta_candidate, theta_hat, gradf_i_batch, f_i_grad_list, x, y)
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgldcvps_gradients1 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgldcvps.sgldcv_ps_grad(subkey, theta_candidate, theta_hat, gradf_0, gradf_i_batch, grad_full_hat, f_i_grad_list, probs3, x, y, n)
            sgldcvps_gradients1[k] = grad
        pseudo_var['sgld-cv-exact'][i,j] = np.sum(np.var(sgldcvps_gradients1, axis = 0))

 Theta candidates tested: 100%|██████████| 10/10 [17:38<00:00, 105.81s/it]


### SGLD-CV-PS (approximate probabilities) gradients

In [39]:
#sgldps (approx) gradients
probs4 = np.zeros(N)
for i in range(N):
    #iterate over datapoints
    hess_mat_i = f_i_hess_list[i]
    p = jnp.linalg.norm(hess_mat_i, ord='fro')
    probs4[i] = np.array(p)
probs4 /= np.sum(probs4)

In [41]:
pseudo_var['sgld-cv-approx'] = np.zeros((n_candidate, batch_sizes.shape[0])) 
for i in tqdm(range(n_candidate), desc = "Theta candidates tested"):
    theta_candidate = theta_candidates[i]
    for j in range(batch_sizes.shape[0]):
        n = batch_sizes[j]
        sgldcvps_gradients2 = np.zeros((reps, dim))
        for k in range(reps):
            key, subkey = random.split(key)
            grad = sgldcvps.sgldcv_ps_grad(subkey, theta_candidate, theta_hat, gradf_0, gradf_i_batch, grad_full_hat, f_i_grad_list, probs4, x, y, n)
            sgldcvps_gradients2[k] = grad
        pseudo_var['sgld-cv-approx'][i,j] = np.sum(np.var(sgldcvps_gradients2, axis = 0))

Theta candidates tested: 100%|██████████| 10/10 [17:34<00:00, 105.49s/it]


### Save results 

In [42]:
plot_data = []
for key in pseudo_var:
    smooth_path = pseudo_var[key].mean(axis = 0)
    plot_data.append(smooth_path)
    path_deviation = 2*pseudo_var[key].std(axis = 0)
    under_line = (smooth_path-path_deviation)
    plot_data.append(under_line)
    over_line = (smooth_path+path_deviation)
    plot_data.append(over_line) 
    
df = pd.DataFrame(plot_data).T
df['proportion'] = np.linspace(0.01, 0.99, num = 50)

In [43]:
df

0              1              2              3              4  \
0   170490.580331  160802.218749  180178.941913  166706.518603  152004.181418   
1    55183.369661   52245.001658   58121.737663   53942.583206   51601.848547   
2    33934.767586   32224.296546   35645.238625   31854.337719   30390.057741   
3    24125.367373   22531.546303   25719.188443   22486.214203   21539.409234   
4    18825.956775   17753.767556   19898.145993   16821.976506   16160.904616   
5    15406.481258   14680.711826   16132.250691   13642.439427   13056.501489   
6    12923.629407   12335.988838   13511.269976   11377.963182   10697.365622   
7    11156.481943   10517.301005   11795.662882    9495.138905    9097.380969   
8     9919.882286    9565.016112   10274.748461    8149.212034    7661.062703   
9     8669.929410    8233.136377    9106.722443    7100.658098    6761.866091   
10    8029.182727    7528.124611    8530.240843    6428.443896    6104.200350   
11    7314.478390    6740.807213    7888.149567    5581.774631    5254.009372   
12    6698.309185    6390.877110    7005.741261    5032.477679    4829.486182   
13    6240.663996    5907.617624    6573.710369    4521.738819    4358.956797   
14    5843.932988    5529.202902    6158.663074    4105.543057    3823.990944   
15    5439.096558    5109.904755    5768.288361    3672.381757    3459.459366   
16    5183.311732    4895.593370    5471.030093    3445.061389    3329.898639   
17    4787.525456    4465.404495    5109.646416    3091.636620    3011.007623   
18    4565.926853    4245.606654    4886.247052    2873.436957    2702.714438   
19    4304.670455    4132.287132    4477.053777    2589.251017    2492.650490   
20    4111.817673    3852.884287    4370.751060    2427.558174    2311.204835   
21    3923.436262    3695.926622    4150.945901    2252.795556    2108.581599   
22    3771.380377    3638.175634    3904.585120    2053.733690    1940.621615   
23    3572.465557    3423.389914    3721.541201    1898.123547    1815.736821   
24    3437.169043    3238.946283    3635.391804    1731.750560    1661.744157   
25    3292.418645    3069.903738    3514.933551    1631.016537    1535.592717   
26    3213.469378    3023.915517    3403.023239    1480.293060    1378.138142   
27    3038.203787    2865.551681    3210.855894    1391.990145    1340.351033   
28    2904.106531    2732.143963    3076.069099    1263.202908    1172.398902   
29    2866.983880    2758.455666    2975.512094    1168.878829    1105.549198   
30    2761.692662    2701.102328    2822.282996    1072.924717    1016.654485   
31    2663.456998    2533.684232    2793.229765     988.809030     952.155049   
32    2568.074003    2527.026866    2609.121141     905.475988     867.367967   
33    2511.259862    2374.961558    2647.558166     819.851116     782.093429   
34    2425.664402    2254.696271    2596.632534     751.433812     719.970389   
35    2369.040423    2258.732363    2479.348483     683.589746     651.082917   
36    2294.732443    2198.361507    2391.103379     622.361532     590.614854   
37    2212.843265    2119.409567    2306.276963     561.691499     531.473152   
38    2165.583249    2038.516585    2292.649913     506.628172     478.174542   
39    2126.692272    2000.988248    2252.396295     456.465352     434.746952   
40    2065.360642    1916.913467    2213.807817     395.833258     367.509805   
41    2028.057284    1941.532567    2114.582001     347.140147     337.491803   
42    1978.933757    1906.139050    2051.728464     299.756619     283.191977   
43    1936.856666    1826.681185    2047.032148     254.715818     249.077917   
44    1883.560174    1776.026068    1991.094280     207.436915     197.685257   
45    1830.027933    1763.042104    1897.013763     164.749212     153.216132   
46    1816.043661    1714.688120    1917.399202     125.495114     119.015377   
47    1761.500846    1676.837872    1846.163821      86.778254      81.705036   
48    1765.648963    1670.135134    1861.162791

In [44]:
path_out = "./out/toy_lrb_gradient_comp.csv"
df.to_csv(path_out, index = False) #save csv